---
title: "Analysing Airline Dataset using Sentiment analysis and Price prediction in python"
author: "Members : Ayush  ,Kritika Jaimini,Rishi  ,Sohini Bhadra, Sneha Karmakar"
date: "2024-04-06"
output: pdf_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
library(htmlwidgets)
library(IRdisplay)
library(ggplot2)
library(plotly)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

## Executive Summary

In this report, we will perform price prediction and sentiment analysis using R and python. We will first gather historical price data, then build a predictive model to forecast future prices. 



We study different columns of the table and try to co-relate them with others and find a relation between those two.

We try to find and analyze those key factors like class of travel, duration of fight, etc. which helps us understand the pricing of tickets to plan and schedule our air travel in efficient way.

Additionally, we will analyze sentiment data from the obtained dataset to gauge sentiment of customers.

# Price Prediction

## Table of Contents

### 1. Introduction

1.1 Overview

1.2 Questions we imposed

1.3 Scope of Analysis

### 2. Explaining the Dataset

2.1 Overview of Dataset

2.2 Problems with the dataset


### 3. Data collection and methods

3.1 Data Sources

3.2 Variables Considered

3.3 Data Preprocessing



### 4. Visualizing the dataset

4.1 Libraries used in the process

4.2 Plots we have used

4.3 Plot of  Number of flights of Airlines in India.

4.4 Plot of Ticket Costs

4.5 Plot of Duration of flights

4.6 Plot on Tickets booked beffore X days

4.7 Plot of Departure time and Arrival time

4.8 Plot on Airline ticket price based on the source and destination cities.

4.9 Plot of Distribution of most Airlines in economy class

4.10 Plot of Total price by Airline in economy class

4.11 Plot of source city in economy class.

4.12 Plot of most airlines in bussiness class and outcome.

4.13 Plot of cities used bussines class tickets

4.14 Correlation Heatmap

4.15 


#### 5. Modeling

### 6. Conclusion

### 7. References

## 1.Introduction

### 1.1 Overview
In this part of project, we study the data which is in tabular format using various Python libraries like Pandas, Numpy, Matplotlib and Seaborn.

We study different columns of the table and try to co-relate them with others and find a relation between those two.

We try to find and analyze those key factors like class of travel, duration of fight, etc. which helps us understand the pricing of tickets to plan and schedule our air travel in efficient way

### 1.2 Questions We imposed

-  What are number of flights operated by each airline?
-  What is price range according to class of travel?
-  What is availability of Tickets according to class of travel?
-  What is price of ticket for different airlines based on duration of flight?
-  How do ticket prices vary across different airlines and class of travel?
-  How do airline ticket prices vary depending on when you buy them?
- How does price of ticket vary depending on duration?
- How does ticket price vary according to departure time and arrival time?
-  How does ticket price vary depending on source and destination?
- How does price of tickets vary based on no. of stops and airline?



### 1.3 Scope of Analysis
The study covers detailed exploratory data analysis on different key factors of an Indian Airline Dataset.

The project also enables us to predict the price of different airlines based on different factors using LINEAR REGRESSION MODEL.



### 2. Explaing the dataset

2.1  Overview of Dataset


The dataset is a .csv file format that we have obtained from google search 
The dataset consits of 3000154 rows and 12 columns.



In airline column there are 6 unique airlines: SpiceJet, AirAsia, Vistara, GO_FIRST, Indigo, Air_India
In source_city & destination_city there are 6 unique cities: Delhi, Mumbai, Bangalore, Kolkata, Hyderabad, Chennai
In arrival & departure columns there are 6 different timings: Night, Morning, Early_Morning, Afternoon, Evening, Late_Night
In class column there are 2 different classes: Economy, Business

2.2 Problems with the Dataset

The main problem with Dataset is that the data is two to three years old so the price prediction might not match the current scenario of prices of airline tickets.



3. Data collection and methods

3.1 Data source 

Data is being derived from Google search.

3.2 Variables Considered
The various features of the dataset are explained below:

- Airline: The name of the airline company is stored in the airline column. It is a categorical feature having 6 different airlines.

- Flight: Flight stores information regarding the plane's flight code. It is a categorical feature.

- Source City: City from which the flight takes off. It is a categorical feature having 6 unique cities.

- Departure Time: This is a derived categorical feature obtained created by grouping time periods into bins. It stores information about the departure time and have 6 unique time labels.

- Stops: A categorical feature with 3 distinct values that stores the number of stops between the source and destination cities.

- Arrival Time: This is a derived categorical feature created by grouping time intervals into bins. It has six distinct time labels and keeps information about the arrival time.

- Destination City: City where the flight will land. It is a categorical feature having 6 unique cities.

- Class: A categorical feature that contains information on seat class; it has two distinct values: Business and Economy.

- Duration: A continuous feature that displays the overall amount of time it takes to travel between cities in hours. 10)Days Left: This is a derived characteristic that is calculated by subtracting the trip date by the booking date.

- Price: Target variable stores information of the ticket price.


3.3 Data Preprocessing

For model fitting data is preprocessed using LabelEncoder from sklearn.preprocessing module.


- we have transform the'airline','source_city','destination_city','departure_time','arrival_time','stops','class' column of dataframe 'df'using 'fit_transform' method involving fitting a LabelEncoder on data and then transforming it

- We have dropped the column 'unnamed'
 from dataframe 'df'

- We have drop the coumn 'flight' from dataset which is of no use to us in modelling.



 4. Visualizing the dataset
 

4.1 Libraries used in the process
- matplotlib
- seaborn



4.2 Plots we have used
- bar graphs
- line graphs
- pie charts
- strip plot
- scatter plot

4.3 Plot of  Number of flights of Airlines in India.

we draw this plot using sns.countplot for 'airline' column.




- From the plot , we can see 'Vistara' has maximum no. of fights followed by 'Air India' while 'Spice Jet' has least no. of flights

4.4 Plot of Ticket Costs

The seaborn. stripplot() method is used to draw a scatter plot where one of variables passed as argument is a categorical variable.Here the categorical variable is "class of travel". From the above figure, we can see 'Economy' class tickets usually cost between 2500 - 22500 while 'Business' class tickets usually cost between 25000 - 95000


4.5 Plot of Duration of flights


This shows  the distribution of ticket price varying with duration of flight. More no. of green and brown points in the figure is explained by the fact that 'Vistara' and 'Air India' have maximum no. of flights. Clearly , Indigo has more no of short duration flights at comaparatively cheaper price.


4.6 Plot on Tickets booked before X days

This plot concludes  that ticket price rise slowly till 20 days from the date of flight, then rise sharply till the last day, while dramatically reducing just 1 day before the date of flight. This can be explained by the fact that people usually buy flight tickets within 2-3 weeks of flight which generates more profits for airlines. On last day, prices show dramatic reduction as airlines hope to fill the flight completely due to increase the load factor and decrease the operational cost per passenger.

4.7 Plot of Departure time and Arrival time

This plot concludes that flights departing late at night are cheapest while those arriving early morning and late night are cheap too. Flights departung in afternoon are relatively cheap as well.



4.8 Plot on Airline ticket price based on the source and destination cities.

 This plot shows that flight departing from Delhi are usually cheaper which can be explained by the fact that Delhi being capital has very strong connectivity with every other city and more no. of freqencies resulting in cheaper ticket prices. Chennai-Bangalore seems to be the most expensive route to fly while Hyderabad is most expensive city to fly.




4.9 Plot of Distribution of most Airlines in economy class

This plots gives us insight about distribition of most Airlines in economy class.

Distribution of Airlines in economy class is as follows:

- Air India : 23.2%
- Indigo : 20.9%
- Go First : 11.2%
- Air Asia : 7.8%
- Spicejet : 4.4%
- Vistara : 32.6%




4.10 Plot of Total price by Airline in economy class

This barplot shows toatl price by Airline.

-Vistara : $525,173,099.00
-Air India: $351,012,862.00
-Indigo : $229,580,207.00
- Go First : $130,973,972.00
- Air Asia : $65,858,089.00
-Spicejet : $55,681,482.00



4.11 Plot of source city in economy class.
The pie chart provides us detail that delhi is the source city for economy class follows by Mumbai.

 

4.12 Plot of most airlines in bussiness class and outcome.



4.13 Plot of cities used bussines class tickets
The pie chart provides us detail that Mumbai  is the source city for bussiness class follows by Delhi.




4.14 Correlation Heatmap

The correlation heatmap describes correlation among various fetures of the dataset.



5. Modeling

The model is trained on basic Linear Regression model.

We imported test_train_test_split form sklearn.model_selection modeule.

Then we imported LinearRegression classifier from linear_model.
We have split the dataset fopr training and testing. 80% data is used for training and 20% data is used for testing the model.

After fitting the model we predicted the prices of flight tickets on testing data.
We also evaluted Mean Absolute Error, Mean Square Error,Mean Absolute Percentage Error.



6. Coclusion

For the linear regression model on dataset following are the concusions:

-train score 0.9048254651102412

-test score 0.9047473929854847

-r2 score 0.9047473929854847

-MAE 4650.70263783112

-MSE 49101030.427204736

-MAPR 0.443777705784786


 7. References






